batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241144
train_epochs: 1000
train_workers: 20
vocab: O?8ZfVRj1GwsPx-4(znDUtT"0p7XW#goy&H,Lad.*5h6YS9cE;:rbJAKkFC/vQBq+iM' !3l)mI2euN
width: 1408
