batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241150
train_epochs: 1000
train_workers: 20
vocab: kvFL9KmseA-Ul.rf(*Zq/cpQ)ahuG;PJ,?M0Yb1jySX:W8i5TIo7!H+tCEn"VxR Dd&34g2#6O'NwzB
width: 1408
