batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241124
train_epochs: 1000
train_workers: 20
vocab: kuCf1.EgG#xOVjMYK*(LibHl:0acdQ7zUhevrToP3/!5)-'D WB89Nt?&msR;ZywAIqp"+4FJS,nX26
width: 1408
