batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405281144
train_epochs: 1000
train_workers: 20
vocab: A,t5Wy2;IH4lbGh:."/oxsNSwOaQq73jU&( fLJmR6EZd!g*i'K#-c0TerzY?nBF9uPp+V1X)MCk8vD
width: 1408
