batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241139
train_epochs: 1000
train_workers: 20
vocab: .O)1wW;aNC(Jdpjg?Kxl"I7sq3imS-4L*zoe+yXb6UF9HBhED0GTk& fQ'/YrAn2tcZuV8#M5R!,v:P
width: 1408
