batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241049
train_epochs: 1000
train_workers: 20
vocab: DsVftz?1uHwA&/IpLN*og!K9JZYX"vPc4E.Q'xTqMd,Fr)2a8 SWGk6;b5OC:Uynm-#hlie+7Bj3(R0
width: 1408
