batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241155
train_epochs: 1000
train_workers: 20
vocab: Z*juY(N:3Kd'0"rAo5tT Oc;R/,I7zsamFWlh9Sf#i)wCM!6Hb.Dvq+?nx1XGg-kB&J2yVL4pPUeEQ8
width: 1408
