batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241209
train_epochs: 1000
train_workers: 20
vocab: lbhCBIX5c+aqJ8sH!utemxTj93o7)6w0WiL,Q(VEO;MYA:.R"rKD d-z'#Z*v12S/g?UPyFGfnk4Np&
width: 1408
