batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202406171355
train_epochs: 1000
train_workers: 20
vocab: .w7EK&4,?Jvs-WNfaG#Ix*M"kHcVmDr3L5tCFR0uh/:QopSTn+b1g26(UdqPi8X9;)yY!B 'AljezZO
width: 1408
