batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241114
train_epochs: 1000
train_workers: 20
vocab: U;zx)t6'1be-&uLTc:EYd?RZifl.N2H5BFD!0 MQ+m*g(XIaVwk/Jh9Os,W#vSAPoq7K4j3G8pC"nyr
width: 1408
