batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405231544
train_epochs: 1000
train_workers: 20
vocab: PirXm/ &5guOUjd-;LtD:lk?"3yJaE27hNq1Rc.pT6C0vY+Mz)Sb'HIoZs,n4xA8#GfWBF!wK(V9e*Q
width: 1408
