batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241141
train_epochs: 1000
train_workers: 20
vocab: qGK7aSeAC:.1N4+k8DQP/v,M&oR!Ucpb-nLOt s(Xx*h2JElmg6)?Wr"3Y5zFwiBZHyT#fuVj0d'I;9
width: 1408
