batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241137
train_epochs: 1000
train_workers: 20
vocab: '"m.R94YkIWz:v#Jy2?3OT/Vx)cp7&5K''SGjPAMlfqnor8(,!BFg-;bE1uNe+DhXsZ*tHw0UdLaCi
  Q6'
width: 1408
