batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241206
train_epochs: 1000
train_workers: 20
vocab: bPnXNS9L'/Tsht0F-zOQg7A8124+VRic 5mDYa!yUp,rKGdo)*J(f3ZwH6qkIMvC:#Wx.uE;lB"?&je
width: 1408
