batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241138
train_epochs: 1000
train_workers: 20
vocab: '!BH*Q5u?D:&/2RzbX3gcpm"J0Gs+''ENY4A6KTifjq8dVWU,(;aoFvwtC-7)ryOIe. n1ZLkPx#MS9hl'
width: 1408
