batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241156
train_epochs: 1000
train_workers: 20
vocab: 6#O)m+RD.5(!cQBl:u3zd/SpXsWveYV9?7xFwM KnHZLC4oJaN2;hiArjg8'UbP*f,GI1q-"EykT0t&
width: 1408
