batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405281158
train_epochs: 1000
train_workers: 20
vocab: )P9fT1HYgk*UO,/sv.e?zo0wx7+QaN6-4d(;MimycDGnWX"EjlbIhqRZV 38ApF:Lr5K2J#u'BC!&St
width: 1408
