batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241120
train_epochs: 1000
train_workers: 20
vocab: 5B,L0.r#OkK4XDymo'&GYci9xZqbR s?dP-V68:UQCASv2;!t7(gTMhu"Hf+)3NI/w1EJalpzFe*jnW
width: 1408
