batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202405241145
train_epochs: 1000
train_workers: 20
vocab: '"6n(QrsT)R/yg-b KLMc43hXB''I.,ESVjzDCwtJ&72q9aW8oiONvepZFAYUkxGu0f:?d!m5PH;*+l#1'
width: 1408
